//types
export const ADD_CHAT = "DIALOGS:ADD_CHAT";
export const DELETE_CHAT = "DIALOGS:DELETE_CHAT";

export const GET_CHATS_START = "DIALOGS:GETCHATS_START"
export const GET_CHATS_SUCCESS = "DIALOGS:GETCHATS_SUCCESS"
export const GET_CHATS_ERROR = "DIALOGS:GETCHATS_ERROR"
