//types
export const UPDATE_NAME = "PROFILE::UPDATE_NAME";
export const UPDATE_SURNAME = "PROFILE::UPDATE_SURNAME";
export const CHANGE_VISIBLE = "PROFILE::CHANGE_VISIBLE";
export const UPDATE_PROFILE="PROFILE::UPDATE_ALL"